version: "2"
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
  web:
    build: .
    environment:
      NODE_ENV: production
      PORT: 8081
      POSTGRES_HOST: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    stdin_open: true # -i
    tty: true # -t
